import 'package:flutter/widgets.dart';

/// Small, app-owned UI dictionary. French is the default for CSPH Cameroon;
/// English remains available in Settings. Unknown copy stays visible as-is so
/// new text is never hidden by a missing translation.
String appString(BuildContext context, String english) {
  if (Localizations.localeOf(context).languageCode != 'fr') return english;
  return _french[english] ?? english;
}

const Map<String, String> _french = {
  'StandUp': 'CSPH • StandUp',
  'Timer': 'Rappels',
  'Org Health': 'Santé de l’organisation',
  'Org': 'Org.',
  'Stand Up': 'Se lever',
  'Snooze': 'Reporter',
  'Preferences & Settings': 'Préférences et paramètres',
  'Frequency Interval': 'Fréquence',
  'Appearance & Styling': 'Apparence',
  'App Theme Mode': 'Thème de l’application',
  'System': 'Système',
  'Light': 'Clair',
  'Dark': 'Sombre',
  'Color Accent System': 'Couleur d’accentuation',
  'Sounds & Haptics': 'Sons et vibrations',
  'Acoustic Chimes': 'Sons de rappel',
  'Play melodic alert on break cadence':
      'Jouer un son mélodieux au moment de la pause',
  'Preview Chime': 'Aperçu du son',
  'Play Chime': 'Écouter',
  'Account': 'Compte',
  'Workspace': 'Espace de travail',
  'Invite code connects your account to organization insights.': 'Le code d’invitation relie votre compte aux indicateurs de votre organisation.',
  'Join': 'Rejoindre',
  'Cloud Sync & Privacy': 'Synchronisation et confidentialité',
  'Contribute Statistics': 'Partager des statistiques',
  'Share anonymized daily counts with employer':
      'Partager des totaux quotidiens anonymisés avec l’employeur',
  'Supabase Cloud Sync': 'Synchronisation Supabase',
  'Sync Now': 'Synchroniser',
  'Replay 10-Slide Onboarding Tour': 'Revoir la présentation en 10 étapes',
  'Reminder Cadence': 'Rythme des rappels',
  'Language': 'Langue',
  'French': 'Français',
  'English': 'Anglais',
  'Home': 'Accueil',
  'Analytics': 'Statistiques',
  'Organization': 'Organisation',
  'Settings': 'Paramètres',
  'SHORTCUTS': 'RACCOURCIS',
  'I Stood Up!': 'Je me suis levé·e !',
  'I stood up!': 'Je me suis levé·e !',
  'Snooze 10m': 'Rappel dans 10 min',
  'Skip': 'Passer',
  'Reminder': 'Rappel',
  'Start stretch': 'Commencer les étirements',

  'A MOMENT TO RESET': 'UNE PAUSE POUR SE RECHARGER',
  'Start 5-Min Guided Stretch Routine':
      'Commencer les étirements guidés (5 min)',
  "Today's Activity": 'Activité du jour',
  '5-Min Guided Stretch': 'Étirements guidés (5 min)',
  'Finish & Log Stand': 'Terminer et enregistrer',
  'Cancel': 'Annuler',
  'Stand Duration Trend': 'Durée des pauses debout',
  'Action Distribution': 'Répartition des actions',
  'Wellness Analytics': 'Statistiques de bien-être',
  'Consistency & Adherence': 'Régularité et assiduité',
  'Contribution Heatmap': 'Carte des pauses',
  'GitHub-style hourly movement matrix':
      'Activité quotidienne sur les 12 derniers mois',
  'Weekly Cadence Breakdown': 'Bilan hebdomadaire',
  'Daily completed vs snoozed vs skipped':
      'Pauses terminées, reportées et ignorées',
  'Active minutes per day over past 14 days':
      'Minutes actives par jour sur les 14 derniers jours',
  'Less': 'Moins',
  'More': 'Plus',
  'Organization Insights': 'Indicateurs de l’organisation',
  'Organization insights are unavailable':
      'Les indicateurs de l’organisation ne sont pas disponibles',
  'ADMIN VIEW': 'VUE ADMINISTRATEUR',
  'Aggregated anonymized health benchmarks powered by Supabase views.':
      'Indicateurs de santé agrégés et anonymisés, fournis par Supabase.',
  'Privacy-Enforced: RLS hides individual timestamps & employee names.': 'Confidentialité renforcée : les règles RLS masquent les noms et les horaires individuels.',
  'Department Adherence Leaderboard': 'Assiduité par service',
  'Peak Skip Hours Analysis': 'Heures où les rappels sont le plus ignorés',
  'HEALTH & WELLNESS CADENCE': 'BIEN-ÊTRE AU TRAVAIL • CSPH CAMEROUN',
  'StandUp Ergonomics': 'Bouger mieux au travail',
  'The Sedentary Trap': 'Les effets de la sédentarité',
  'The 5-Minute Solution': 'La pause de 5 minutes',
  'Personalize Profile': 'Votre profil',
  'Department': 'Service',
  'Organization Workspace': 'Espace de travail de l’organisation',
  'Preferences & Cadence': 'Préférences et rythme',
  'Reminder Frequency': 'Fréquence des rappels',
  'Color Accent': 'Couleur d’accentuation',
  'Sound Chimes': 'Sons de rappel',
  'Play relaxing chimes on break alerts':
      'Jouer un son apaisant lors des rappels',
  'Play Preview Chime': 'Écouter un aperçu',
  'System Permissions': 'Autorisations du système',
  'Privacy by Design': 'La confidentialité dès la conception',
  'Contribute to Org Statistics':
      'Contribuer aux statistiques de l’organisation',
  'You Are Ready!': 'Tout est prêt !',
  'Launch StandUp Experience': 'Découvrir StandUp',
  'Edit Employee Profile': 'Modifier le profil',
  'Save': 'Enregistrer',
  'Sign-in link sent. Check your email to continue.':
      'Lien de connexion envoyé. Consultez votre boîte mail pour continuer.',
  'Email me a sign-in link': 'M’envoyer un lien de connexion',
  'Google': 'Google',
  'Apple': 'Apple',
  'Join your workspace': 'Rejoindre votre espace',
  'Join workspace': 'Rejoindre l’espace',
  'OR': 'OU',
  'Check your email to confirm your account, then sign in here.': 'Confirmez votre compte depuis votre boîte mail, puis connectez-vous ici.',
  'Employee health & wellness': 'Santé et bien-être au travail',
  'Stand': 'Pause debout',
  'Good Morning': 'Bonjour',
  'Good Afternoon': 'Bon après-midi',
  'Good Evening': 'Bonsoir',
  'Time for a movement break': 'C’est le moment de bouger',
  'Take a posture moment': 'Prenez un instant pour votre posture',
  '5 minutes of movement restores spinal fluids and reduces fatigue.': 'Cinq minutes de mouvement aident à réduire la fatigue et à délier le dos.',
  'Let your shoulders soften and your spine settle comfortably.':
      'Détendez vos épaules et redressez-vous confortablement.',
  'Team Member': 'Membre de l’équipe',
  'General': 'Général',
  'Permissions Enabled ✓': 'Autorisations activées ✓',
  'Enable Notifications & Alarms': 'Activer les notifications et alarmes',
  'Create your account': 'Créer votre compte',
  'Sign in to StandUp': 'Se connecter à StandUp',
  'Create account': 'Créer un compte',
  'I have an account': 'J’ai déjà un compte',
  'Sign in': 'Se connecter',
  'Connect': 'Connecter',
  'Sign out': 'Se déconnecter',
  'Using this device': 'Utilisation hors ligne sur cet appareil',
  'Sign in to turn on account sync':
      'Connectez-vous pour activer la synchronisation',
  'Your account is securely connected':
      'Votre compte est connecté de façon sécurisée',
  'Cloud accounts need Supabase project keys':
      'La connexion cloud nécessite les clés du projet Supabase',
  'Account connected': 'Compte connecté',
  'No workspace linked': 'Aucun espace associé',
  'Workspace linked': 'Espace associé',
  'Enter the invite code provided by your organization.':
      'Saisissez le code d’invitation fourni par votre organisation.',
  'Gentle reminders to move for 5 minutes every hour, combat sedentary strain, and keep your body energised at work.': 'Des rappels doux vous invitent à bouger cinq minutes chaque heure, à réduire les tensions et à préserver votre énergie au travail.',
  'Sitting continuously for 6+ hours daily compresses the lumbar spine, decreases blood circulation by 50%, and causes chronic posture fatigue.': 'Rester assis plus de six heures par jour sollicite le bas du dos, ralentit la circulation et accentue la fatigue posturale.',
  'Spinal Compression': 'Tensions dans le dos',
  'Lumbar strain & shoulder stiffness': 'Raideurs lombaires et épaules tendues',
  'Metabolic Sluggishness': 'Ralentissement métabolique',
  'Drop in circulation & calorie burn':
      'Circulation et dépense énergétique réduites',
  'Energy Crashes': 'Baisse d’énergie',
  'Afternoon brain fog & posture slump': 'Fatigue et posture affaissée',
  'Standing and stretching for just 5 minutes every hour resets your musculoskeletal balance, revives oxygen to the brain, and keeps posture aligned.': 'Cinq minutes debout et quelques étirements chaque heure aident à délier le corps, à retrouver de l’énergie et à garder une posture confortable.',
  '+32% Sustained Focus': 'Concentration prolongée',
  'Oxygen boost resets mental clarity':
      'Une pause aide à retrouver de la clarté mentale',
  'Zero Lower Back Strain': 'Soulager le bas du dos',
  'Intervertebral discs decompress': 'Le dos peut se relâcher',
  'Passive Caloric Health': 'Bouger au quotidien',
  'Engages major stabilizer muscle groups':
      'Mobilise les principaux muscles stabilisateurs',
  'A frictionless rhythm engineered around deep work without intrusive disruption.':
      'Un rythme discret, pensé pour respecter vos périodes de concentration.',
  'Enter your work details to unlock department wellness benchmarks.': 'Renseignez votre profil professionnel pour consulter les indicateurs de bien-être de votre service.',
  'Join your company workspace to see collective progress and contribute only the daily totals you choose to share.': 'Rejoignez l’espace de votre organisation pour suivre les progrès collectifs et choisir les totaux quotidiens que vous partagez.',
  'Detected Workspace:': 'Espace détecté :',
  'After onboarding, connect your account in Settings and use the invite code provided by your organization.': 'Après la présentation, connectez votre compte dans les paramètres et saisissez le code d’invitation de votre organisation.',
  'Customize your reminder schedule, audio tones, and color palette.': 'Choisissez la fréquence des rappels, les sons et la couleur de l’application.',
  'We believe employee health monitoring must never compromise personal autonomy.': 'Le suivi du bien-être ne doit jamais porter atteinte à votre vie privée.',
  'Help leadership understand posture wellness trends.': 'Aidez l’organisation à comprendre les tendances de bien-être, sans partager vos détails individuels.',
  'stands': 'pauses debout',
  'Adherence': 'Assiduité',
  'breaks': 'pauses',
  'minutes': 'minutes',
  'times': 'fois',
  'Stand Time': 'Temps debout',
  'Average Stand / Day': 'Moyenne debout / jour',
  '8-hour workday target': 'objectif sur 8 h de travail',
  'days': 'jours',
  'tracked days': 'jours suivis',
  'Completed': 'Terminées',
  'Snoozed': 'Reportées',
  'Skipped': 'Ignorées',
  'Tap any square to inspect details. Green: completed • Amber: snoozed • Red: skipped': 'Touchez une case pour voir le détail. Vert : terminée • Ambre : reportée • Rouge : ignorée',
  'It\'s time to stand up! Your body will thank you.':
      'C’est le moment de vous lever ! Votre corps vous remerciera.',
  'Time-level activity stays private on employee devices.':
      'Les horaires individuels restent privés sur les appareils des employés.',
  'Hours with the most skipped reminders.':
      'Heures où les rappels sont le plus souvent ignorés.',
  'active members': 'membres actifs',
  'stands completed': 'pauses debout terminées',
  'skips': 'rappels ignorés',
  'Workspace membership is optional. Your individual reminder history stays on this device.': 'L’adhésion à l’espace est facultative. Votre historique individuel reste sur cet appareil.',
  'To wake you up exactly when 50 or 60 minutes elapse, StandUp needs permission to send local alerts and schedule exact timers.': 'Pour vous rappeler de bouger à l’heure choisie, StandUp doit pouvoir envoyer des notifications et programmer les rappels.',
  'Your first cadence cycle has been initialized. Stand up when you hear the gentle chime, stretch your arms, and reclaim your daily vitality.': 'Votre première séquence de rappels est prête. Le son vous invitera à vous lever, à vous étirer et à reprendre votre activité avec énergie.',
  '100% Local Drift Database': 'Données locales sur l’appareil',
  'Exact reminder timestamps & skip logs stay strictly on your device.': 'Les horaires des rappels et votre historique restent sur votre appareil.',
  'Anonymized Aggregates': 'Données agrégées et anonymisées',
  'Only daily counts (e.g. 7 stands completed) sync to Supabase for company metrics.': 'Seuls des totaux quotidiens (par exemple, sept pauses terminées) sont transmis à Supabase.',
  'ORG HEALTH': 'BIEN-ÊTRE CSPH',
  'Organization health insights': 'Indicateurs de bien-être de l’organisation',
  'How StandUp Works': 'Comment fonctionne StandUp',
  'Gentle Scheduled Chimes': 'Des rappels doux',
  'Soft acoustic tones notify you when it is time to rise.':
      'Un son discret vous rappelle qu’il est temps de vous lever.',
  'One-Tap Actions': 'Des actions en un geste',
  '"I Stood Up" logs 5 min active time. "Snooze 10m" pauses if you are presenting.': '« Je me suis levé·e » enregistre cinq minutes actives. Reportez le rappel de dix minutes si vous êtes en réunion.',
  'Intelligent Nudge Logic': 'Des encouragements bienveillants',
  'If you skip 3 times, StandUp gently reminds you why your back needs relief.': 'Après plusieurs rappels ignorés, StandUp vous encourage doucement à prendre soin de votre dos.',
  'GitHub-Style Analytics': 'Un suivi de vos habitudes',
  'Watch your consistency matrix glow with emerald green squares.':
      'Visualisez la régularité de vos pauses dans un calendrier coloré.',
  'Production Flutter + Supabase + Drift':
      'Application Flutter + Supabase + Drift',
  'EMPLOYEE HEALTH & WELLNESS CADENCE':
      'SANTÉ ET BIEN-ÊTRE AU TRAVAIL • CSPH CAMEROUN',
  'Org Adherence': 'Assiduité de l’organisation',
  'Auto': 'Auto',
  'Continue': 'Continuer',
  // Preferences — new rows
  'Team': 'Équipe',
  'Your team': 'Votre équipe',
  'Workspace label': 'Nom de l’espace de travail',
  'Optional team or workspace name': 'Nom d’équipe ou d’espace (facultatif)',
  'Engineering': 'Ingénierie',
  'Product & Design': 'Produit et Design',
  'Marketing & Sales': 'Marketing et Ventes',
  'People & Ops': 'RH et Opérations',
  'Finance': 'Finance',
  'Leadership': 'Direction',
  'Member': 'Membre',
  'Employee User': 'Collaborateur',
  'No email linked': 'Aucune adresse e-mail associée',
  'Daily stand goal': 'Objectif de pauses par jour',
  'Target number of stand-ups per day': 'Nombre de pauses visées chaque jour',
  'Notifications': 'Notifications',
  'Allow alerts and exact timers so reminders arrive on time.': 'Autorisez les alertes et les alarmes exactes pour recevoir les rappels à l’heure.',
  'Enable': 'Activer',
  'Notifications are enabled': 'Les notifications sont activées',
  'Notifications were not granted on this device':
      'Les notifications n’ont pas été autorisées sur cet appareil',
  'Quiet hours': 'Heures calmes',
  'Pause reminders during your personal rest window':
      'Suspendre les rappels pendant votre plage de repos',
  'Off': 'Désactivées',
  'Reminder tone': 'Son du rappel',
  'Gentle chime': 'Carillon doux',
  'Bright success': 'Réussite lumineuse',
  'Soft nudge': 'Encouragement léger',
  'Soft click': 'Clic discret',
  'Vibration & Haptics': 'Vibrations et retours haptiques',
  'Use the native vibration on every action':
      'Utiliser la vibration native à chaque action',
  'Background Run': 'Fonctionnement en arrière-plan',
  'Background run': 'Fonctionnement en arrière-plan',
  'Background run enabled': 'Fonctionnement en arrière-plan activé',
  'StandUp can wake on schedule even when the app is closed.': 'StandUp peut se réveiller à l’heure prévue même si l’application est fermée.',
  'Allow background activity': 'Autoriser l’activité en arrière-plan',
  'Your device may delay reminders. Grant the battery exemption for exact timing.': 'Votre appareil peut retarder les rappels. Accordez l’exemption de batterie pour une horaire précise.',
  'On Android, allow StandUp to ignore battery optimisation for exact reminders.': 'Sur Android, autorisez StandUp à ignorer l’optimisation de la batterie pour des rappels précises.',
  'Allow': 'Autoriser',
  'Export my data': 'Exporter mes données',
  'A CSV summary of your daily stand-up history, generated on this device.': 'Un résumé CSV de votre historique quotidien de pauses, généré sur cet appareil.',
  'Copy CSV to clipboard': 'Copier le CSV dans le presse-papiers',
  'CSV copied to your clipboard': 'CSV copié dans le presse-papiers',
  'StandUp v1.0.0 • Production Flutter + Supabase + Drift':
      'CSPH StandUp v1.0.0 • Flutter + Supabase + Drift',
  'Your progress': 'Votre progression',
  'Leaderboard': 'Classement',
  'Level': 'Niveau',
  'XP': 'XP',
  'Day streak': 'Jours de suite',
  'Weekly ranking': 'Classement hebdomadaire',
  'Offline — showing your personal bests':
      'Hors ligne — voici vos records personnels',
  'You': 'Vous',
  // Analytics
  'Sync to Supabase': 'Synchroniser avec Supabase',
  'Completed breaks': 'Pauses terminées',
  'total': 'au total',
  'Current Streak': 'Série en cours',
  'Syncing...': 'Synchronisation...',
  'Supabase Synced': 'Synchronisé avec Supabase',
  'Offline Queue': 'File hors ligne',
  'Sync Pending': 'Synchronisation en attente',
  'Cloud Connected': 'Cloud connecté',
  'Local-only until Supabase Auth is configured':
      'Hors ligne tant que Supabase Auth n’est pas configuré',
  'Synchronizing in progress...': 'Synchronisation en cours...',
  'Daily totals synced': 'Totaux quotidiens synchronisés',
  'Sync failed; your local data is safe':
      'Échec de la synchronisation ; vos données locales sont intactes',
  // Org admin
  'Active Employees': 'Collaborateurs actifs',
  'Enrolled teammates': 'Collègues inscrits',
  'Completion benchmark': 'Objectif de complétion',
  'Stands Logged': 'Pauses enregistrées',
  'mins movement': 'min de mouvement',
  'Skipped Breaks': 'Pauses ignorées',
  'snoozed': 'reportées',
  'Refresh Org Aggregates': 'Actualiser les données de l’organisation',
  'This requires a Supabase account with an organization administrator role...': 'Cette vue nécessite un compte Supabase avec le rôle d’administrateur de l’organisation…',
  'This requires a Supabase account with an organization administrator role and a linked workspace.': 'Cette vue nécessite un compte Supabase avec le rôle d’administrateur de l’organisation et un espace de travail associé.',
  // Guided stretch routine
  '1. Overhead Reach & Spinal Stretch':
      '1. Étirement allongé & colonne vertébrale',
  'Interlace fingers, reach palms upward towards ceiling, lengthen spine and breathe deeply for 60 seconds.': 'Entrelacez vos doigts, montez les paumes vers le plafond, étirez la colonne et respirez profondément pendant 60 secondes.',
  '2. Chest Opener & Shoulder Retraction':
      '2. Ouverture de la poitrine & rétractation des épaules',
  'Clasp hands behind lower back, pull shoulders down and back, lift chin gently, expanding lungs.': 'Joignez les mains dans le bas du dos, tirez les épaules vers le bas et l’arrière, levez doucement le menton pour ouvrir les poumons.',
  '3. Standing Quad & Hip Flexor Stretch':
      '3. Étirement des quadriceps & des fléchisseurs de la hanche',
  'Hold desk for balance, grasp right ankle behind you for 30s, then switch to left ankle.': 'Appuyez-vous au bureau pour l’équilibre, saisissez la cheville droite derrière vous pendant 30 s, puis changez de côté.',
  '4. Standing Calf Raises': '4. Montées sur pointes debout',
  'Slowly rise onto balls of both feet, hold 2 seconds, lower slowly. Repeat 15 times.': 'Montez lentement sur la pointe des pieds, tenez 2 secondes, redescendez lentement. Répétez 15 fois.',
  '5. Gentle Torso Twists': '5. Rotations douces du torse',
  'With feet shoulder-width apart, gently rotate torso left and right with arms relaxed.': 'Pieds écartés à la largeur des épaules, faites tourner doucement le torse à gauche et à droite, bras détendus.',
  // Leaderboard
  'to next level': 'avant le niveau suivant',
  'Department standings from anonymized daily totals.':
      'Classement par service, à partir de totaux quotidiens anonymisés.',
  'Complete your first break to join the standings.':
      'Terminez votre première pause pour rejoindre le classement.',
  'Goal': 'Objectif',
  'Your best days': 'Vos meilleurs jours',
  // Action window
  'Movement window open': 'Fenêtre de mouvement ouverte',
  'Next movement window': 'Prochaine fenêtre de mouvement',
  'Log your stand-up before the window closes':
      'Enregistrez votre pause avant la fermeture',
  'A break only counts in the last minutes of each hour':
      'Une pause n’est comptée que dans les dernières minutes de chaque heure',
  'Not inside the movement window': 'Hors de la fenêtre de mouvement',
  'Action window': 'Fenêtre d’action',
  'Restrict stand-ups to the last minutes of each hour':
      'Limiter les pauses aux dernières minutes de chaque heure',
  'Enforce the action window': 'Appliquer la fenêtre d’action',
  'When on, a stand-up only counts inside the window.':
      'Si activée, une pause n’est comptée que dans la fenêtre.',
  'When off, a stand-up is accepted at any time.':
      'Si désactivée, une pause est acceptée à tout moment.',
  'Window length': 'Durée de la fenêtre',
  'Open this many minutes before the hour ends':
      'Ouvrir ce nombre de minutes avant la fin de l’heure',
  // Device profile
  'Device & app': 'Appareil et application',
  'This device': 'Cet appareil',
  'What this device reports': 'Ce que cet appareil transmet',
  'Everything below is read from your operating system and stored on this device. No IP address, location, or advertising identifier is ever collected.': 'Les données ci-dessous proviennent de votre système d’exploitation et restent sur cet appareil. Aucune adresse IP, localisation ou identifiant publicitaire n’est collecté.',
  'Copy device details': 'Copier les détails',
  'Device details copied': 'Détails de l’appareil copiés',
  'Clock integrity': 'Intégrité de l’horloge',
  'Clock looks normal': 'Horloge normale',
  'The device clock has moved repeatedly, so totals are flagged as unreliable for the leaderboard.': 'L’horloge de l’appareil a été modifiée à plusieurs reprises ; les totaux sont donc signalés comme non fiables pour le classement.',
};
